### PR TITLE
Add get_primary_host_name

### PR DESCRIPTION
**Pull request by olsonpm**
- add supporting tests

this commit supports the config.get('me') refactoring done
in haraka/Haraka#2380

### CODE REVIEW

**Comment by msimerson** [comment]
Thanks @olsonpm. Would you mind also bumping the version number in `package.json` and updating Changes. Then I'll merge and publish the new release.

**Comment by olsonpm** [comment]
for sure, i'll have it done in a couple hours

**Comment by olsonpm** [comment]
Ah I'm unfamiliar with when github decides to send notifications - this is a bump in case the push earlier didn't notify.

**Comment by msimerson** [comment]
````
$ npm publish
+ haraka-net-utils@1.1.0
````

**Pull request merged**
