### PR TITLE
Add enableSNI option, default false

### PR DESCRIPTION
**Pull request by typingArtist**
Before creating SNI functionality in Haraka itself, we need to have the option to enable/disable it, for main section, outbound and inbound alike.

### CODE REVIEW

**Comment by typingArtist** [comment]
@msimerson, could you create a new release, e.g. 1.0.5 for that change, please, so I can change dependencies in a PR on Haraka once the new flag is used.

**Comment by msimerson** [comment]
Go ahead and also update the version in package.json and the Changes file. Then no more PRs are required for us to release the next version. Also, if you update your branch then I think you'll find that build tests also pass.

**Comment by msimerson** [comment]
@typingArtist , you shouldn't need the WS commit. Just update your branch against master.

**Comment by msimerson** [comment]
````
$ npm publish
+ haraka-net-utils@1.0.5
````

**Comment by typingArtist** [comment]
@msimerson, thanks for merging. However, I don’t understand why you think that the WS commit was not necessary. I updated from master, yet linting failed.

**Comment by msimerson** [comment]
Well, I *thought* I had already done that, in master, but maybe I hadn't.

**Comment by typingArtist** [comment]
okay, then. :smile:

**Pull request merged**
