### PR TITLE
stop is_private_ip from checking if the IP is bound to a local network interface

### LINKED ISSUE #41: no GeoIP results for local_ip
After upgrading to the Haraka 2.8.24, haraka-plugin-geoip is now logging this error, "no GeoIP results for local_ip!"
I tracked it down to get_geoip() which calls net_utils.is_private_ip(), which calls net_utils.is_local_ip(), which returns true for my server's public IP address.

### PR DESCRIPTION
**Pull request by baudehlo**
Fixes #41

### CODE REVIEW

**Comment by baudehlo** [comment]
@msimerson due to this bug we should probably delete 1.1.3 from npm. Thoughts?

**Comment by msimerson** [comment]
Also, we can't delete from npm. IIRC, there is an "unpublish" feature or something like that.

**Comment by msimerson** [comment]
````
$ npm publish
npm notice 
npm notice 📦  haraka-net-utils@1.1.4
npm notice === Tarball Contents === 
npm notice 1.1kB  package.json                           
npm notice 137B   .codeclimate.yml                       
npm notice 212B   .eslintrc.json                         
npm notice 238B   .travis.yml                            
npm notice 395B   appveyor.yml                           
npm notice 1.6kB  Changes.md                             
npm notice 13.4kB index.js                               
npm notice 1.1kB  LICENSE                                
npm notice 2.9kB  README.md                              
npm notice 490B   run_tests                              
npm notice 424B   test/config/dhparams.pem               
npm notice 14B    test/config/me                         
npm notice 1.2kB  test/config/tls_cert.pem               
npm notice 1.7kB  test/config/tls_key.pem                
npm notice 900B   test/config/tls.ini                    
npm notice 3.1kB  test/config/tls/haraka.local.pem       
npm notice 3.1kB  test/config/tls/haraka2.local.pem      
npm notice 7.1kB  test/config/tls/mail.theartfarm.com.pem
npm notice 36.8kB test/net_utils.js                      
npm notice === Tarball Details === 
npm notice name:          haraka-net-utils                        
npm notice version:       1.1.4                                   
npm notice package size:  24.5 kB                                 
npm notice unpacked size: 75.8 kB                                 
npm notice shasum:        8b42c72f6875c25f3fde38c6775805f960f85be5
npm notice integrity:     sha512-/wJ5kRJJHqyAE[...]KR1R+wdXuiYlg==
npm notice total files:   19                                      
npm notice 
+ haraka-net-utils@1.1.4
````

**Comment by msimerson** [comment]
````
$ npm unpublish haraka-net-utils@1.1.3
-haraka-net-utils@1.1.3
````

**Pull request merged**
